# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='message',
            field=models.CharField(default='jsd', max_length=20),
            preserve_default=False,
        ),
    ]
